export const START_FETCHING = 'START_FETCHING';
export const STOP_FETCHING = 'STOP_FETCHING';
export const FOLLOW = 'FOLLOW';
export const UNFOLLOW = 'UNFOLLOW';

// app
export const INITIALIZE_THE_APPLICATION = "INITIALIZE_THE_APPLICATION";
export const REFRESH_REQUEST = "REFRESH_REQUESTS";
export const TOGGLE_NAVIGATION_PANEL = "TOGGLE_NAVIGATION_PANEL";
export const OPEN_MAIN_CONTROL_PANEL = "OPEN_MAIN_CONTROL_PANEL";
export const OPEN_QUEST_PAGE_CONTROL_PANEL = "OPEN_QUEST_PAGE_CONTROL_PANEL";
export const OPEN_OWNER_PAGE_CONTROL_PANEL = 'OPEN_OWNER_PAGE_CONTROL_PANEL';

// auth
export const SET_USER_DATA = "SET_USER_DATA";
export const SIGN_IN = "SIGN_IN";
export const SIGN_UP = "SIGN_UP";
export const LOG_OUT = "LOG_OUT";
export const GET_CAPTCHA = "GET_CAPTCHA";

// messages
export const SEND_MESSAGE = 'SEND-MESSAGE';

//dialogs
export const START_COMMUNICATION = 'START_COMMUNICATION';
export const GET_DIALOGS = 'GET_ALL_DIALOGS';
export const GET_MESSAGES = 'GET_MESSAGES';

// profile
export const ADD_POST = 'ADD-POST';
export const SET_USER_PROFILE = 'SET_USER_PROFILE';
export const GET_STATUS = 'GET_STATUS';
export const UPDATE_STATUS_TEXT = 'UPDATE_STATUS_TEXT';
export const SET_FLAG_LOOKING_AT_MY_PROFILE = 'SET_FLAG_LOOKING_AT_MY_PROFILE';
export const SET_FLAG_NOT_LOOKING_AT_MY_PROFILE = 'SET_FLAG_NOT_LOOKING_AT_MY_PROFILE';
export const UPDATE_PROFILE_PICTURE = 'UPDATE_PROFILE_PICTURE';
export const SAVE_PROFILE = 'SAVE_PROFILE';

// users
export const SET_USERS = 'SET_USERS';
export const SET_TOTAL_USERS_COUNT = 'SET_TOTAL_USERS_COUNT';
export const TOGGLE_IS_FETCHING = 'TOGGLE_IS_FETCHING';
export const IS_FETCHING_FOLLOW_OR_UNFOLLOW_START = 'IS_FETCHING_FOLLOW_OR_UNFOLLOW_START';
export const IS_FETCHING_FOLLOW_OR_UNFOLLOW_END = 'IS_FETCHING_FOLLOW_OR_UNFOLLOW_END';
export const FETCHING_GET_USERS_CARDS_START = 'FETCHING_GET_USERS_CARDS_START';
export const FETCHING_GET_USERS_CARDS_END = 'FETCHING_GET_USERS_CARDS_END';
export const FETCHING_GET_USERS_COUNT_START = 'FETCHING_GET_USERS_COUNT_START';
export const FETCHING_GET_USERS_COUNT_END = 'FETCHING_GET_USERS_COUNT_END';